<dialog id="{{ $id }}" data-dialog-modal class="m-auto w-[calc(100%-2rem)] max-w-lg rounded-lg border border-[#eadfe0] bg-white p-0 text-[#111827] shadow-[0_24px_70px_rgba(17,24,39,0.22)] backdrop:bg-[#111827]/45">
    <form action="{{ $action }}" method="POST" class="p-5 sm:p-6">
        @csrf
        @if ($method !== 'POST') @method($method) @endif
        <div class="flex items-start justify-between gap-4"><div><h2 class="text-lg font-bold text-[#111827]">{{ $title }}</h2><p class="mt-1 text-sm text-[#667085]">Informe os dados da criança vinculada.</p></div><button type="button" data-dialog-close class="inline-flex h-8 w-8 items-center justify-center rounded-lg text-[#667085] hover:bg-[#f7edef]" aria-label="Fechar"><x-gmdi-close-o class="h-5 w-5" /></button></div>
        <div class="mt-5 space-y-5"><label class="block"><span class="text-sm font-semibold text-[#344054]">Nome</span><input name="nome" type="text" value="{{ old('nome', $child?->nome) }}" class="mt-2 h-11 w-full rounded-[8px] border border-[#e4d8d9] px-3 text-sm shadow-sm outline-none focus:border-[#ef5b97]" required>@error('nome') <span class="mt-1 block text-xs text-[#c2414b]">{{ $message }}</span> @enderror</label><label class="block"><span class="text-sm font-semibold text-[#344054]">Data de nascimento</span><input name="data_nascimento" type="date" value="{{ old('data_nascimento', $child?->data_nascimento?->format('Y-m-d')) }}" class="mt-2 h-11 w-full rounded-[8px] border border-[#e4d8d9] px-3 text-sm shadow-sm outline-none focus:border-[#ef5b97]" required>@error('data_nascimento') <span class="mt-1 block text-xs text-[#c2414b]">{{ $message }}</span> @enderror</label><div><x-material.select name="sexo" label="Sexo" :options="$sexOptions" :selected="old('sexo', $child?->sexo)" placeholder="Selecione" required />@error('sexo') <span class="mt-1 block text-xs text-[#c2414b]">{{ $message }}</span> @enderror</div></div>
        <div class="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" data-dialog-close class="inline-flex h-10 items-center justify-center rounded-lg border border-[#e4d8d9] bg-white px-4 text-sm font-semibold text-[#344054] hover:bg-[#fbfaf9]">Cancelar</button><button type="submit" class="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-[#ef5b97] px-4 text-sm font-semibold text-white hover:bg-[#d94889]"><x-lucide-save class="h-4 w-4" /> Salvar bebê</button></div>
    </form>
</dialog>
