<article class="overflow-hidden rounded-[8px] border border-[#eadfe0] bg-white shadow-[0_14px_35px_rgba(28,25,23,0.05)]">
    <div class="border-b border-[#f0e7e8] p-5"><div class="flex items-start gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-[8px] bg-[#ecfdf3] text-[#23845a]"><x-lucide-clipboard-list class="h-5 w-5" /></span><div><h3 class="text-lg font-bold text-[#111827]">Registro clínico</h3><p class="mt-1 text-sm text-[#667085]">Resumo, objetivo, avaliação e conduta definida pela equipe.</p></div></div></div>
    <div class="grid gap-5 p-5 md:grid-cols-2">
        <label class="block md:col-span-2"><span class="text-sm font-semibold text-[#344054]">Resumo</span><input type="text" name="summary" value="{{ old('summary', $attendanceData['summary']) }}" class="{{ $inputClass }}" placeholder="Ex.: Orientações sobre amamentação e pega correta">@error('summary') <span class="mt-1 block text-xs text-[#c2414b]">{{ $message }}</span> @enderror</label>
        <label class="block md:col-span-2"><span class="text-sm font-semibold text-[#344054]">Objetivo</span><textarea name="objective" class="{{ $textareaClass }}">{{ old('objective', $attendanceData['objective']) }}</textarea>@error('objective') <span class="mt-1 block text-xs text-[#c2414b]">{{ $message }}</span> @enderror</label>
        <label class="block"><span class="text-sm font-semibold text-[#344054]">Queixa principal</span><textarea name="complaint" class="{{ $textareaClass }}">{{ old('complaint', $attendanceData['complaint']) }}</textarea>@error('complaint') <span class="mt-1 block text-xs text-[#c2414b]">{{ $message }}</span> @enderror</label>
        <label class="block"><span class="text-sm font-semibold text-[#344054]">Avaliação</span><textarea name="evaluation" class="{{ $textareaClass }}">{{ old('evaluation', $attendanceData['evaluation']) }}</textarea>@error('evaluation') <span class="mt-1 block text-xs text-[#c2414b]">{{ $message }}</span> @enderror</label>
        <label class="block md:col-span-2"><span class="text-sm font-semibold text-[#344054]">Conduta</span><textarea name="conduct" class="{{ $textareaClass }}">{{ old('conduct', $attendanceData['conduct']) }}</textarea>@error('conduct') <span class="mt-1 block text-xs text-[#c2414b]">{{ $message }}</span> @enderror</label>
    </div>
</article>
<article class="overflow-hidden rounded-[8px] border border-[#eadfe0] bg-white shadow-[0_14px_35px_rgba(28,25,23,0.05)]">
    <div class="border-b border-[#f0e7e8] p-5"><div class="flex items-start gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-[8px] bg-[#fff7e6] text-[#b76b00]"><x-lucide-forward class="h-5 w-5" /></span><div><h3 class="text-lg font-bold text-[#111827]">Observações</h3><p class="mt-1 text-sm text-[#667085]">Informações complementares para acompanhamento interno.</p></div></div></div>
    <div class="p-5"><label class="block"><span class="text-sm font-semibold text-[#344054]">Observações internas</span><textarea name="notes" class="{{ $textareaClass }}">{{ old('notes', $attendanceData['notes']) }}</textarea>@error('notes') <span class="mt-1 block text-xs text-[#c2414b]">{{ $message }}</span> @enderror</label></div>
</article>
